services:
  server:
    container_name: hello_server
    build: hello_server
  
  nginx:
    container_name: nginx
    image: nginx:latest
    ports:
      - "80:8080"
    volumes:
      - "./nginx.conf:/etc/nginx/nginx.conf"